config/routes.rb
Rails.application.routes.draw do
  resources :tassks
  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tassk.rb
class Tassk < ApplicationRecord
    validates :name, :details,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  end

  def goodbye
  end
end

app/controllers/tassks_controller.rb
class TassksController < ApplicationController
  before_action :set_tassk, only: %i[ show edit update destroy ]

  # GET /tassks or /tassks.json
  def index
    @tassks = Tassk.all
  end

  # GET /tassks/1 or /tassks/1.json
  def show
  end

  # GET /tassks/new
  def new
    @tassk = Tassk.new
  end

  # GET /tassks/1/edit
  def edit
  end

  # POST /tassks or /tassks.json
  def create
    @tassk = Tassk.new(tassk_params)

    respond_to do |format|
      if @tassk.save
        format.html { redirect_to @tassk, notice: "Tassk was successfully created." }
        format.json { render :show, status: :created, location: @tassk }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tassk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tassks/1 or /tassks/1.json
  def update
    respond_to do |format|
      if @tassk.update(tassk_params)
        format.html { redirect_to @tassk, notice: "Tassk was successfully updated." }
        format.json { render :show, status: :ok, location: @tassk }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tassk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tassks/1 or /tassks/1.json
  def destroy
    @tassk.destroy
    respond_to do |format|
      format.html { redirect_to tassks_url, notice: "Tassk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tassk
      @tassk = Tassk.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tassk_params
      params.require(:tassk).permit(:name, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tassks_helper.rb
module TassksHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>Welcome to home</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

app/views/say/hello.html.erb
<h1>Say#hello</h1>
<p>Find me in app/views/say/hello.html.erb</p>

app/views/tassks/_form.html.erb
<%= form_with(model: tassk) do |form| %>
  <% if tassk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tassk.errors.count, "error") %> prohibited this tassk from being saved:</h2>

      <ul>
        <% tassk.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_field :details %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tassks/edit.html.erb
<h1>Editing Tassk</h1>

<%= render 'form', tassk: @tassk %>

<%= link_to 'Show', @tassk %> |
<%= link_to 'Back', tassks_path %>

app/views/tassks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tassks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Details</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tassks.each do |tassk| %>
      <tr>
        <td><%= tassk.name %></td>
        <td><%= tassk.details %></td>
        <td><%= link_to 'Show', tassk %></td>
        <td><%= link_to 'Edit', edit_tassk_path(tassk) %></td>
        <td><%= link_to 'Destroy', tassk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tassk', new_tassk_path %>

app/views/tassks/new.html.erb
<h1>New Tassk</h1>

<%= render 'form', tassk: @tassk %>

<%= link_to 'Back', tassks_path %>

app/views/tassks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tassk.name %>
</p>

<p>
  <strong>Details:</strong>
  <%= @tassk.details %>
</p>

<%= link_to 'Edit', edit_tassk_path(@tassk) %> |
<%= link_to 'Back', tassks_path %>